### ISSUE TITLE
CanvasRenderingContext2D::set_strokeStyle(const String&) missing

### ISSUE THREAD

**Issue by opatry** [leaningtech/cheerp-libs#1]
Hi,

first of all, sorry if this issue is not in the right repository, I saw that [leaningtech/cheerp-utils](https://github.com/leaningtech/cheerp-utils) contains the header file for [`clientlib.h`](https://github.com/leaningtech/cheerp-utils/blob/master/include/client/clientlib.h) but no issue tracker in this one.

So, I think I need `CanvasRenderingContext2D::set_strokeStyle(const String&)` to set the stroke color when using `context->stroke()`.
Still, `CanvasRenderingContext2D::set_fillStyle(const String&)` is available and works fine.

What is the purpose (and how to use it) of the alternative taking `client::Object*`?

Thanks

**Comment by alexp-sssup** [comment]
CanvasRenderingContext2D::set_strokeStyle(const String&) was indeed missing. I've just pushed the fix to the repository. You can still use the current constructor by creating a String object with your desired style, for example ctx->set_strokeStyle(new client::String("color: black"))

In general we track bugs using Launchpad https://bugs.launchpad.net/cheerp/

**Comment by opatry** [comment]
Ok, thanks for the fix.

Regarding the `Object*` API usage, who is responsible for the object deletion? And if it's caller, when is it safe to delete it?

**Comment by alexp-sssup** [comment]
It's a JS object implemented by the browser, so its life cycle in managed by the GC.
Il 07/nov/2015 11:39 PM, opatry <notifications@github.com> ha scritto:Ok, thanks for the fix.

Regarding the Object* API usage, who is responsible for the object deletion? And if it's caller, when is it safe to delete it?
